### ISSUE TITLE
CODE REVIEW

### ISSUE THREAD

**Issue by Amoshalt** [PolytechLyon/isi3-tp2-visiteur-tardy-tp2#1]
Bonsoir,
Pourriez vous me dire quels sont les défauts de mon travail sur ce TP s'il vous plait.
Merci d'avance.

**Comment by Slashgear** [comment]
- C'est pas trop mal, le rapport est bien

- Peux tu me dire ici quel est le use case du pattern visiteur ?

- La priorité sous forme de booléen c'est pas cool. Une priorité au sens mathématique c'est pas vrai ou faux. C'est assez dangereux de représenter des choses qui ne sont pas vrai/faux par des booléen.
Il faudrait soit: passer par un ENUM de Priorité ou passer par un type

- Un rangement en package (nom de package en minuscule)

**Comment by Slashgear** [comment]
Petit UP ici @Amoshalt !

**Comment by Amoshalt** [comment]
Bonjour, comme je vous ai expliqué lors du dernier TP, je m'excuse de ne pas avoir encore répondu, je ne les oublie pas mais étant très occupé par l'ensemble des tps à rendre ainsi que autres projets/tps des autres matières je n'ai pas encore trouvé le temps de me pencher dessus. Je commencerai à vous répondre dès que j'ai un peu de temps. Merci de votre compréhension.
Bonne journée.

**Comment by Amoshalt** [comment]
Bonsoir,

Le cas du pattern visiteur:
On utilise le pattern visiteur dans le cas où l'on veut parcourir un ensemble de données (un arbre par exemple) et où les données ne sont pas du même type et/ou seront traitées spécifiquement.

J'ai rangé en deux packages, un package opérateur contenant Visitable et les opérateurs et un autre package comprenant les visiteur ainsi que l'interface Visiteur.

J'ai aussi modifier ma condition booléenne par un type String.

Pourriez vous me redonner un avis quand vous aurez le temps sur mon update s'il vous plait.

**Comment by Slashgear** [comment]
La priorité ça ne me plait toujours pas 😢 

Les chaines de caractères c'est pas cool au milieu du code.

Tu dois te rendre compte ici que si on rajoute des types de noeuds, ça va vitre être le bazar.

**Comment by Amoshalt** [comment]
Bonjour, 
Je vous avais mal compris la dernière fois j'ai changé la priorité, je la fait maintenant grâce à une énumération. Est-ce que cela vous convient ?

**Comment by Slashgear** [comment]
ça reste plus lisible que des *magic numbers* au milieu du code.
